### ISSUE TITLE
IntegerNumberPicker ( Horizontal ) Width Not Change

### ISSUE THREAD

**Issue by gizemay96** [caglarylmz/awesome_number_picker#1]
Hi @caglarylmz  , I want change width of horizontal integer numberpicker. But i dont know how can i make this.

Just like below picture.

<img width="664" alt="Screen Shot 2022-09-15 at 12 28 55" src="https://user-images.githubusercontent.com/61078410/190368841-0592762a-eed0-484e-bc0f-f9c427370aea.png">

**Comment by caglarylmz** [comment]
Hi @gizemay96 . You can use size property for width. But when I was writing the code, I only thought about vertical usage and set a width. When I thought about this situation for horizontal use, I should have set it as height. There is a bug here. i will fix this problem when i have time

**Comment by gizemay96** [comment]
@caglarylmz  Thank you so much for your response.
